### PR TITLE
Expand SQL formatter to LakeFormation

### PR DESCRIPTION
**Pull request by LeonLuttenberger**
### Feature or Bugfix
- Feature

### Detail
- Expand SQL formatter to LakeFormation

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by malachi-constant** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: GitHubDistributedCodeBuild6-jWcl5DLmvupS
* Commit ID: 60e371febe9e0da06de8214708856080131da470
* Result: FAILED
* [Build Logs](https://p0rshq9q5i.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=53d84425-657a-4712-af50-9df4cb63abf3%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by malachi-constant** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: GitHubLoadTests5656BB24-s6u9F3qN9oFy
* Commit ID: 60e371febe9e0da06de8214708856080131da470
* Result: SUCCEEDED
* [Build Logs](https://pciyom2pbh.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=66d7f9a5-f6e4-4c5a-868b-11fa361cf4ca%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by malachi-constant** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: GitHubStandardCodeBuild8C06-llutOAimTATs
* Commit ID: 60e371febe9e0da06de8214708856080131da470
* Result: FAILED
* [Build Logs](https://jsv9u8gote.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=75e39cdf-1316-4c58-b110-0dbfb819a9a7%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by malachi-constant** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: GitHubDistributedCodeBuild6-jWcl5DLmvupS
* Commit ID: c1309ea4867bd37b2fbff604ecda2a66ca2434aa
* Result: SUCCEEDED
* [Build Logs](https://p0rshq9q5i.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=512c3354-f12c-440f-a222-96caff6c736b%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by malachi-constant** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: GitHubDistributedCodeBuild6-jWcl5DLmvupS
* Commit ID: 23cdef49b16ca655d31fe2a5a093f6d254b970d9
* Result: SUCCEEDED
* [Build Logs](https://p0rshq9q5i.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=36e12988-c306-46a8-81f3-3e3195d585a5%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by malachi-constant** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: GitHubLoadTests5656BB24-s6u9F3qN9oFy
* Commit ID: c1309ea4867bd37b2fbff604ecda2a66ca2434aa
* Result: SUCCEEDED
* [Build Logs](https://pciyom2pbh.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=59ec1f9c-3441-44cf-835a-c9545b1c7efd%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by malachi-constant** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: GitHubStandardCodeBuild8C06-llutOAimTATs
* Commit ID: c1309ea4867bd37b2fbff604ecda2a66ca2434aa
* Result: SUCCEEDED
* [Build Logs](https://jsv9u8gote.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=57a011c8-03c1-46c7-8e64-8ff0914ed738%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by malachi-constant** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: GitHubLoadTests5656BB24-s6u9F3qN9oFy
* Commit ID: 23cdef49b16ca655d31fe2a5a093f6d254b970d9
* Result: SUCCEEDED
* [Build Logs](https://pciyom2pbh.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=b868db73-922c-4ff7-944c-928f79a73189%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by malachi-constant** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: GitHubStandardCodeBuild8C06-llutOAimTATs
* Commit ID: 23cdef49b16ca655d31fe2a5a093f6d254b970d9
* Result: SUCCEEDED
* [Build Logs](https://jsv9u8gote.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=57e76ef2-d5db-4f1b-91c8-c9aa65b2f931%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Review by jaidisido — COMMENTED** [review]
I believe LakeFormation uses Redshift Spectrum under the hood so I don't believe the Presto Engine definition we have would work for conditions like [IN](https://docs.aws.amazon.com/redshift/latest/dg/r_in_condition.html). Could we please just check that we don't need to create a new Engine definition for it? Looks good otherwise, thanks!

**Comment by LeonLuttenberger** [comment]
> I believe LakeFormation uses Redshift Spectrum under the hood so I don't believe the Presto Engine definition we have would work for conditions like [IN](https://docs.aws.amazon.com/redshift/latest/dg/r_in_condition.html). Could we please just check that we don't need to create a new Engine definition for it? Looks good otherwise, thanks!

@jaidisido The only difference I found between how the engines handle literals was that in how Presto and Hive escape string quotations. However, PartiQL does it the same way that Presto does (`'` within a string is escaped as `''`).

I'm not sure what you mean by `IN` though? Presto and PartiQL seem to have the same syntax for `IN` (values separated by commas enclosed by parenthesis). There is an issue here thought that customers have no way of passing us a list of parameters that go into `IN`, and have us parse it as such.

For example, if they give us
```python
sql="SELECT * FROM table WHERE id IN :ids",
params={"ids": [1, 2, 3]}
```
we will parse this as `SELECT * FROM table WHERE id IN ARRAY[1, 2, 3]`. This query would therefore be invalid for both Presto and PartiQL. I'm not sure how to solve this gap though, as we need to parse lists as arrays.

**Review by malachi-constant — COMMENTED** [review]
LGTM, holding off on approval until discussion started by @jaidisido is resovled.

**Comment by jaidisido** [comment]
> > I believe LakeFormation uses Redshift Spectrum under the hood so I don't believe the Presto Engine definition we have would work for conditions like [IN](https://docs.aws.amazon.com/redshift/latest/dg/r_in_condition.html). Could we please just check that we don't need to create a new Engine definition for it? Looks good otherwise, thanks!
> 
> @jaidisido The only difference I found between how the engines handle literals was that in how Presto and Hive escape string quotations. However, PartiQL does it the same way that Presto does (`'` within a string is escaped as `''`).
> 
> I'm not sure what you mean by `IN` though? Presto and PartiQL seem to have the same syntax for `IN` (values separated by commas enclosed by parenthesis). There is an issue here thought that customers have no way of passing us a list of parameters that go into `IN`, and have us parse it as such.
> 
> For example, if they give us
> 
> ```python
> sql="SELECT * FROM table WHERE id IN :ids",
> params={"ids": [1, 2, 3]}
> ```
> 
> we will parse this as `SELECT * FROM table WHERE id IN ARRAY[1, 2, 3]`. This query would therefore be invalid for both Presto and PartiQL. I'm not sure how to solve this gap though, as we need to parse lists as arrays.

The Array one is tricky indeed, but I meant for even simpler examples like `dt.datetime`, this would parse to `TIMESTAMP '...'` which I don't believe would be accepted in a partiql LakeFormation/Redshift query. I think we need to test this formatter against some actual queries submitted to the engine to determine our gaps

**Comment by malachi-constant** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: GitHubDistributedCodeBuild6-jWcl5DLmvupS
* Commit ID: 3e0d7ec35b5cff9545aef8ead88371f100585979
* Result: SUCCEEDED
* [Build Logs](https://p0rshq9q5i.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=4479556d-26a5-440d-83dd-b95c5e249a5e%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by malachi-constant** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: GitHubLoadTests5656BB24-s6u9F3qN9oFy
* Commit ID: 3e0d7ec35b5cff9545aef8ead88371f100585979
* Result: SUCCEEDED
* [Build Logs](https://pciyom2pbh.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=341a9f41-0240-4fdc-92df-574fbfbb5829%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by malachi-constant** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: GitHubStandardCodeBuild8C06-llutOAimTATs
* Commit ID: 3e0d7ec35b5cff9545aef8ead88371f100585979
* Result: FAILED
* [Build Logs](https://jsv9u8gote.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=d516e4a5-94fe-45b5-8fb3-e817dd6c25ff%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by malachi-constant** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: GitHubDistributedCodeBuild6-jWcl5DLmvupS
* Commit ID: d0f375a94bd30f0e349f448af454e37529df702d
* Result: SUCCEEDED
* [Build Logs](https://p0rshq9q5i.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=729519d1-5957-4dab-8302-6ad475a92535%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by malachi-constant** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: GitHubLoadTests5656BB24-s6u9F3qN9oFy
* Commit ID: d0f375a94bd30f0e349f448af454e37529df702d
* Result: SUCCEEDED
* [Build Logs](https://pciyom2pbh.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=e865f388-43bb-46f4-b434-659af1aa0c28%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by malachi-constant** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: GitHubStandardCodeBuild8C06-llutOAimTATs
* Commit ID: d0f375a94bd30f0e349f448af454e37529df702d
* Result: SUCCEEDED
* [Build Logs](https://jsv9u8gote.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=d0f7dc58-daf0-47d4-b696-559f6b5c0b90%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Review by jaidisido — APPROVED** [review]
It looks great, thank you for taking the time to deep dive partiql!

**Pull request merged**
