### PR TITLE
fix: read parquet file in chunked mode per row group

### PR DESCRIPTION
**Pull request by FredericKayser**
### Feature or Bugfix
- Bugfix

### Detail
Fixes the read_parquet function in chunked mode. Currently a whole file gets loaded into the memory instead of row groups. This can lead to memory issues. 

### Relates
- https://github.com/aws/aws-sdk-pandas/issues/3010

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by malachi-constant** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: GitHubCodeBuild8756EF16-4rfo0GHQ0u9a
* Commit ID: cc487506f51970501947cafd4c4036d74574c0fa
* Result: FAILED
* [Build Logs](https://gqgcj9s2gc.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=c0d1bd7d-82d1-4329-b825-9338bc6d2142%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by malachi-constant** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: GitHubDistributedCodeBuild6-jWcl5DLmvupS
* Commit ID: cc487506f51970501947cafd4c4036d74574c0fa
* Result: FAILED
* [Build Logs](https://p0rshq9q5i.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=8aedbbaf-a5e2-42af-94cd-16d84aeff515%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by malachi-constant** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: GitHubCodeBuild8756EF16-4rfo0GHQ0u9a
* Commit ID: 3bad1cde7ac094349f13674debdb1a9c8db0b854
* Result: FAILED
* [Build Logs](https://gqgcj9s2gc.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=e96ba607-352e-40ef-9205-7877d80099e5%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by malachi-constant** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: GitHubDistributedCodeBuild6-jWcl5DLmvupS
* Commit ID: 3bad1cde7ac094349f13674debdb1a9c8db0b854
* Result: FAILED
* [Build Logs](https://p0rshq9q5i.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=1947ba68-5332-48fd-bce9-fcbd264c8e8b%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by malachi-constant** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: GitHubCodeBuild8756EF16-4rfo0GHQ0u9a
* Commit ID: 5d51c451cb51436d82bebdceb1f4349843db5eb4
* Result: SUCCEEDED
* [Build Logs](https://gqgcj9s2gc.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=694a76ba-37bd-44c5-b9b4-d384efc0da5c%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by malachi-constant** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: GitHubDistributedCodeBuild6-jWcl5DLmvupS
* Commit ID: 5d51c451cb51436d82bebdceb1f4349843db5eb4
* Result: SUCCEEDED
* [Build Logs](https://p0rshq9q5i.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=f0c79de3-6b2e-4886-9ff4-15e56738ab98%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by malachi-constant** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: GitHubCodeBuild8756EF16-4rfo0GHQ0u9a
* Commit ID: fecdbd47ad5d4586160dc68b964eceacc7c6c5f2
* Result: SUCCEEDED
* [Build Logs](https://gqgcj9s2gc.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=ba0187c6-0002-455e-b46b-719f9e466355%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by malachi-constant** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: GitHubDistributedCodeBuild6-jWcl5DLmvupS
* Commit ID: fecdbd47ad5d4586160dc68b964eceacc7c6c5f2
* Result: SUCCEEDED
* [Build Logs](https://p0rshq9q5i.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=0a26affd-dd0b-46f9-92f9-17c16de7ba21%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Review by jaidisido — APPROVED** [review]

**Comment by malachi-constant** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: GitHubCodeBuild8756EF16-4rfo0GHQ0u9a
* Commit ID: 5a3289da1cedfcf63792514387957ad731c19989
* Result: SUCCEEDED
* [Build Logs](https://gqgcj9s2gc.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=05041179-32c2-424d-b79e-c174b39dccb8%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by malachi-constant** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: GitHubDistributedCodeBuild6-jWcl5DLmvupS
* Commit ID: 5a3289da1cedfcf63792514387957ad731c19989
* Result: FAILED
* [Build Logs](https://p0rshq9q5i.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=61b73061-3d23-45dd-a546-69672078ae59%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by vhnguyenae** [comment]
Hi @FredericKayser, I'm not sure this is a bug or not but this change broke one of our unit test for empty data frame. 
With awswrangler 3.10.0, `wr.s3.read_parquet(..., chunked = 10)` returns an iterator with len = 0.
But with awswrangler 3.10.1,  `wr.s3.read_parquet(..., chunked = 10)` returns an iterator with len = 1.
It's just a simple debug `print("Hello len iterator_df", len(list(iterator_df)))`
Is it considered a regression? 
If so I can provide more detail if you need more information to investigate.
Thank you

**Comment by FredericKayser** [comment]
Hey @vhnguyenae, in my opinion the new behavior should be intended. This enables the consumer to receive the columns eventough the file has no content rows. Could you maybe share your thoughts why this specific behavior is relevant for you? I think a solid implementation should be able to deal with both variants as you are just receiving an empty data frame.
@kukushking @jaidisido what do you think?

**Comment by vhnguyenae** [comment]
Hi @FredericKayser ,
Thank you for the quick feedback. This is the sample code that I had before to process the data.
In order to keep the old behaviour, I need to add an extra check to make sure the data_frame is not empty before processing it, while with the previous version, the for loop is never entered because the iterator size was 0

```python
    iterator_df = wr.s3.read_parquet(path=s3_path, chunked=10)

    for data_frame in iterator_df:
        # I had to add this extra check in order to fix our test so that we don't process the data of empty dataframe
        if not data_frame.empty:
            data_frame =process_data(data_frame, ....)
```
btw Happy new year 🥳 🎉

**Comment by FredericKayser** [comment]
Hi @vhnguyenae, first of all happy new year :D Is this change just causing trouble with the test, but the productive code still works?

**Comment by vhnguyenae** [comment]
Hi @FredericKayser, we haven't encounter any issue with the production environment yet, but I think the bahavior is also changed if we have to process an empty data frame, since the test case is used to cover that scenario 😁

**Comment by FredericKayser** [comment]
@vhnguyenae Can you maybe explain what your test exactly does and which asserts do you use?

**Comment by vhnguyenae** [comment]
Our process_data did many things, but let just say we add an extra column with hardcode value:
`df['new_column'] = 'random'`

Previous code without empty dataframe check:

```python
    result_df = DataFrame()

    iterator_df = wr.s3.read_parquet(path=s3_path, chunked=10)

    for data_frame in iterator_df:
        data_frame =process_data(data_frame, ....)
    return result_df        
```

If we don't enter the for loop, then `result_df` is empty
If we enter the for loop without empty dataframe check, `process_data` returns a dataframe with the new_column and its new value

So the behavior of our function is changed, instead of returning an empty df, now we return a non empty df with a hardcode column

**Comment by FredericKayser** [comment]
@vhnguyenae Okay, thank you :) So when you just add a hardcoded-column in an empty data frame, the data frame is still empty, but has a new column. My suggestion is that you pre-check the received results from the library and then decide if you run `process_data` with the received data frame or not, because the library just ensures that you receive a DataFrame type or iterator of DataFrames, but not the exact format, so in my opinion this is your responsibility to ensure that there is data in the data frame as there are no guarantees in the specification. This would also lead to more stability and robustness of your code.  

I hope this helps solving your problem :)

**Comment by vhnguyenae** [comment]
Thanks @FredericKayser  for the clarification, that's what I already did in my code 😁

**Pull request merged**
