### PR TITLE
fix: escape column names in PRIMARY KEY statement in SQL query

### LINKED ISSUE #2350: Copying to Redshift fails if one of the primary key columns includes a hyphen
### Describe the bug

Copying to Redshift (`awswrangler.redshift.copy`) fails if one of the primary key columns (`primary_keys`) in the table has a hyphen in its name. The `CREATE TABLE` statement will then fail with the following error message:

> ProgrammingError: {'S': 'ERROR', 'C': '42601', 'M': 'syntax error at or near "-"', 'P': '1026', 'F': '/home/ec2-user/padb/src/pg/src/backend/parser/parser_scan.l', 'L': '732', 'R': 'yyerror'}

This is because when creating the SQL Query for this, the column names are not escaped in the `PRIMARY KEY ()` part.

Since this is an easy fix, I'll also open a PR for this myself today.

### How to Reproduce

Create a pandas data frame where one of the columns is e.g. `my-column-name` and then use this column in the `primary_keys` parameter of the `awswrangler.redshift.copy` method.

### Expected behavior

No error and table is written.

### Your project

_No response_

### Screenshots

_No response_

### OS

Linux

### Python version

3.9

### AWS SDK for pandas version

2.17.0

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mc51**
### Feature or Bugfix
- Bugfix

### Detail
Fixes #2350 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by malachi-constant** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: GitHubCodeBuild8756EF16-4rfo0GHQ0u9a
* Commit ID: 49c19827fe3246fce7be6987dd1d16c2d030957b
* Result: SUCCEEDED
* [Build Logs](https://gqgcj9s2gc.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=4f5d09e7-0f21-4f20-ba6e-9fe0a470dbc8%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by malachi-constant** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: GitHubDistributedCodeBuild6-jWcl5DLmvupS
* Commit ID: 49c19827fe3246fce7be6987dd1d16c2d030957b
* Result: SUCCEEDED
* [Build Logs](https://p0rshq9q5i.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=98668e3e-f670-4b6b-8462-9010680f9383%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Review by LeonLuttenberger — COMMENTED** [review]
Thanks!

It would be good to add a unit test in `tests/unit/test_redshift.py`:

```python
def test_to_sql_with_hyphenated_primary_key(
    redshift_table: str,
    redshift_con: redshift_connector.Connection,
) -> None:
    schema = "public"

    df = pd.DataFrame({"id-col": [1, 2, 3], "other-col": ["foo", "boo", "bar"]})
    df["id-col"] = df["id-col"].astype("Int64")
    df["other-col"] = df["other-col"].astype("string")

    wr.redshift.to_sql(
        df=df, con=redshift_con, table=redshift_table, schema=schema, mode="overwrite", primary_keys=["id-col"]
    )

    df_out = wr.redshift.read_sql_table(table=redshift_table, con=redshift_con, schema=schema)
    assert_pandas_equals(df, df_out)
```

**Comment by malachi-constant** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: GitHubDistributedCodeBuild6-jWcl5DLmvupS
* Commit ID: 89df59d63486cfd7577990be59c0bf7914ff4312
* Result: SUCCEEDED
* [Build Logs](https://p0rshq9q5i.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=11a3a936-6cb7-4d89-8a1b-65dcb6035fb4%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by mc51** [comment]
Sorry for the delay. I've added the test now.

**Comment by malachi-constant** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: GitHubCodeBuild8756EF16-4rfo0GHQ0u9a
* Commit ID: 0a7d28620dda036d218d326112d603d030327527
* Result: SUCCEEDED
* [Build Logs](https://gqgcj9s2gc.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=f3aa4e6d-5e5f-465d-98e0-e7f20c9c5f28%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by malachi-constant** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: GitHubDistributedCodeBuild6-jWcl5DLmvupS
* Commit ID: 0a7d28620dda036d218d326112d603d030327527
* Result: SUCCEEDED
* [Build Logs](https://p0rshq9q5i.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=9943412a-8921-406c-88d9-45d384c563ba%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Review by jaidisido — APPROVED** [review]

**Comment by malachi-constant** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: GitHubDistributedCodeBuild6-jWcl5DLmvupS
* Commit ID: 1ead3a9f4fee090830398a3c52f351d6a5e49cfe
* Result: SUCCEEDED
* [Build Logs](https://p0rshq9q5i.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=006da44c-a0a5-455a-b162-c17ea20de98f%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Pull request merged**
