### PR TITLE
Add distributed mode for test_routines

### PR DESCRIPTION
**Pull request by LeonLuttenberger**
### Feature or Bugfix
- Feature

### Detail
- Making the `test_routines` tests usable in distributed mode

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by malachi-constant** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: GitHubLoadTests5656BB24-s6u9F3qN9oFy
* Commit ID: 76c04e04207372ad9108553db3699f53b29d4cc3
* Result: SUCCEEDED
* [Build Logs](https://pciyom2pbh.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=9fe0fe45-4406-4133-ae12-9418ea5e92d6%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by malachi-constant** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: GitHubStandardCodeBuild8C06-llutOAimTATs
* Commit ID: 76c04e04207372ad9108553db3699f53b29d4cc3
* Result: SUCCEEDED
* [Build Logs](https://jsv9u8gote.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=eca1290e-979f-42c7-a496-c3410fb0b9d1%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by malachi-constant** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: GitHubDistributedCodeBuild6-jWcl5DLmvupS
* Commit ID: 76c04e04207372ad9108553db3699f53b29d4cc3
* Result: SUCCEEDED
* [Build Logs](https://p0rshq9q5i.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=9065f0d9-99a3-4592-94d6-abcd47a47161%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Review by jaidisido — COMMENTED** [review]
I actually skipped this one on purpose because I suspect that running it concurrently has been causing the intermittent failures that we have seen in our Standard tests. `test_catalog` + `test_lakeformation` should cover the same basis as this file also

**Comment by LeonLuttenberger** [comment]
> I actually skipped this one on purpose because I suspect that running it concurrently has been causing the intermittent failures that we have seen in our Standard tests. `test_catalog` + `test_lakeformation` should cover the same basis as this file also

That makes sense. I had a lot of problems getting the tests for my PR yesterday to pass because of issues with `test_routing`. I just figured it was worth it if it gave us extra coverage. But I think you're right, I don't think we're getting any new coverage with these tests.

**Comment by kukushking** [comment]
+1 my observation so far has been that these are the exact tests that almost always fail when standard and distributed CB are running concurrently.

**Pull request closed without merging**
