### PR TITLE
Deps: Remove upper bound limit on 'python' version

### PR DESCRIPTION
**Pull request by malachi-constant**
### Dependency Update
- Remove upper bound limit on 'python' version

### Relates
- #1714 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by LeonLuttenberger — APPROVED** [review]

**Comment by malachi-constant** [comment]
> You will want to regenerate the poetry.lock as a result. Then later we will need to do the same for `release-3.0.0`

Looks like we have this problem upstream, not sure if it's just `isort` or that was just the first package to error out.

```
The current project's Python requirement (>=3.7.1) is not compatible with some of the required packages Python requirement:
  - isort requires Python >=3.6.1,<4.0, so it will not be satisfied for Python >=4.0
  - isort requires Python >=3.6.1,<4.0, so it will not be satisfied for Python >=4.0
  - isort requires Python >=3.6.1,<4.0, so it will not be satisfied for Python >=4.0
  - isort requires Python >=3.6.1,<4.0, so it will not be satisfied for Python >=4.0

Because no versions of isort match >5.9.2,<5.9.3 || >5.9.3,<5.10.0 || >5.10.0,<5.10.1 || >5.10.1,<6.0.0
 and isort (5.9.2) requires Python >=3.6.1,<4.0, isort is forbidden.
And because isort (5.9.3) requires Python >=3.6.1,<4.0
 and isort (5.10.0) requires Python >=3.6.1,<4.0, isort is forbidden.
So, because isort (5.10.1) requires Python >=3.6.1,<4.0
 and awswrangler depends on isort (^5.9.2), version solving failed.

  • Check your dependencies Python requirement: The Python requirement can be specified via the `python` or `markers` properties

    For isort, a possible solution would be to set the `python` property to ">=3.7.1,<4.0"
    For isort, a possible solution would be to set the `python` property to ">=3.7.1,<4.0"
    For isort, a possible solution would be to set the `python` property to ">=3.7.1,<4.0"
    For isort, a possible solution would be to set the `python` property to ">=3.7.1,<4.0"

    https://python-poetry.org/docs/dependency-specification/#python-restricted-dependencies,
    https://python-poetry.org/docs/dependency-specification/#using-environment-markers
```

**Comment by kukushking** [comment]
Upper bound `>=3.7.1,<4.0` seems reasonable - do any other packages complain if you put that in?

**Comment by malachi-constant** [comment]
> Upper bound `>=3.7.1,<4.0` seems reasonable - do any other packages complain if you put that in?

Seems to work fine with`<4.0` as an upper limit.

**Review by cnfait — APPROVED** [review]

**Review by kukushking — APPROVED** [review]
Looks good!

**Review by jaidisido — APPROVED** [review]

**Comment by malachi-constant** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: GitHubCodeBuild8756EF16-4rfo0GHQ0u9a
* Commit ID: 810216395d150d08726d63c85b0b326269a45042
* Result: SUCCEEDED
* [Build Logs](https://gqgcj9s2gc.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=15c6f8cb-100c-4b95-96fa-affcc3934e3b%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Pull request merged**
