### PR TITLE
(enhancement) Minor - add EMR configurations arg

### PR DESCRIPTION
**Pull request by kukushking**
### Relates
- #1938 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by malachi-constant** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: GitHubCodeBuild8756EF16-4rfo0GHQ0u9a
* Commit ID: 0383c2bc48b72d1bb656cc700e3c9705700b3c77
* Result: FAILED
* [Build Logs](https://gqgcj9s2gc.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=2d3281ee-0fce-456f-8c84-8fd3224fea6a%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Review by malachi-constant — APPROVED** [review]
LGTM, although looks like coverage dipped, but I don't see any uncovered lines from your PR in the coverage report.

**Comment by kukushking** [comment]
> LGTM, although looks like coverage dipped, but I don't see any uncovered lines from your PR in the coverage report.

Yeah I think even adding a parameter alone can dip it... I will add a couple more test cases.

**Review by jaidisido — APPROVED** [review]

**Comment by malachi-constant** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: GitHubCodeBuild8756EF16-4rfo0GHQ0u9a
* Commit ID: 3c9b93649655f44ee74023896d8b06307139c075
* Result: SUCCEEDED
* [Build Logs](https://gqgcj9s2gc.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=f5a751fd-cf6a-4c76-8c53-1bd9fff6b88c%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Pull request merged**
