### PR TITLE
Pytest Coverage Workflow

### PR DESCRIPTION
**Pull request by malachi-constant**
## Workflow
- Pytest Coverage Workflow

### Detail 
- Worklow triggers if PR is labeled with `coverage`
- Workflow comments coverage report. 

### Relates
- #1776 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by malachi-constant** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: GitHubCodeBuild8756EF16-4rfo0GHQ0u9a
* Commit ID: faf9e8cf80d4cce7c3709a45429f8d84194d18d6
* Result: FAILED
* [Build Logs](https://gqgcj9s2gc.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=45ae23fb-9f1b-45c0-98a1-a54167ea0b76%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by malachi-constant** [comment]
Let me know what you think about having this "label-driven". We could also just have this as a manual workflow, viewable via the _Actions_ console.

**Comment by LeonLuttenberger** [comment]
> Let me know what you think about having this "label-driven". We could also just have this as a manual workflow, viewable via the _Actions_ console.

Is there a downside to running this on every PR (besides embarrassment because of low coverage :) )?

**Comment by malachi-constant** [comment]
> > Let me know what you think about having this "label-driven". We could also just have this as a manual workflow, viewable via the _Actions_ console.
> 
> Is there a downside to running this on every PR (besides embarrassment because of low coverage :) )?

Yea I think it would be better to opt-in to running this as its a bit verbose for every PR. That's why I did the label conditional on the PR.

**Comment by malachi-constant** [comment]
> How are we going to run this for the distributed version? Are we gonna run a separate coverage report with Ray installed?

I would think for now yes it would be a separate report.

**Comment by kukushking** [comment]
> ### ✅ Result of Pytest Coverage
> ---------- coverage: platform linux, python 3.8.14-final-0 -----------
> 
> Name	Stmts	Miss	Cover
> awswrangler/**init**.py	6	0	100%
> awswrangler/**metadata**.py	4	0	100%
> awswrangler/_config.py	290	98	66%
...

Omg I love this 😍

**Comment by LeonLuttenberger** [comment]
> > > Let me know what you think about having this "label-driven". We could also just have this as a manual workflow, viewable via the _Actions_ console.
> > 
> > 
> > Is there a downside to running this on every PR (besides embarrassment because of low coverage :) )?
> 
> Yea I think it would be better to opt-in to running this as its a bit verbose for every PR. That's why I did the label conditional on the PR.

So will the coverage report get triggered when I add the label? Let's say I've created my PR, all the tests have passed, and now I just wanna run the coverage. Does the action of me adding the label trigger it?

**Comment by kukushking** [comment]
> Is there a downside to running this on every PR (besides embarrassment because of low coverage :) )?

@LeonLuttenberger Polluting the longer PRs with hundreds of comments could be one especially with that comment length

**Comment by malachi-constant** [comment]
> > > > Let me know what you think about having this "label-driven". We could also just have this as a manual workflow, viewable via the _Actions_ console.
> > > 
> > > 
> > > Is there a downside to running this on every PR (besides embarrassment because of low coverage :) )?
> > 
> > 
> > Yea I think it would be better to opt-in to running this as its a bit verbose for every PR. That's why I did the label conditional on the PR.
> 
> So will the coverage report get triggered when I add the label? Let's say I've created my PR, all the tests have passed, and now I just wanna run the coverage. Does the action of me adding the label trigger it?

Exactly. This [label](https://github.com/aws/aws-sdk-pandas/labels/coverage) is added as a [conditional](https://github.com/aws/aws-sdk-pandas/blob/28db4d9cb1e0b4ac5e264a4b86d67c0751a694d2/.github/workflows/pytest-coverage.yml#L16) in the workflow which is [triggered](https://github.com/aws/aws-sdk-pandas/blob/28db4d9cb1e0b4ac5e264a4b86d67c0751a694d2/.github/workflows/pytest-coverage.yml#L7) by a label event against a pr.

**Comment by jaidisido** [comment]
The numbers are off, this the report from the latest CB run:
```
Module | statements | missing | excluded | coverage
-- | -- | -- | -- | --
awswrangler/__init__.py | 6 | 0 | 0 | 100%
awswrangler/__metadata__.py | 4 | 0 | 0 | 100%
awswrangler/_config.py | 283 | 13 | 0 | 95%
awswrangler/_data_types.py | 580 | 119 | 0 | 79%
awswrangler/_databases.py | 149 | 12 | 0 | 92%
awswrangler/_utils.py | 198 | 22 | 0 | 89%
awswrangler/athena/__init__.py | 3 | 0 | 0 | 100%
awswrangler/athena/_cache.py | 116 | 5 | 0 | 96%
awswrangler/athena/_read.py | 219 | 29 | 0 | 87%
awswrangler/athena/_utils.py | 325 | 18 | 0 | 94%
awswrangler/catalog/__init__.py | 6 | 0 | 0 | 100%
awswrangler/catalog/_add.py | 48 | 5 | 0 | 90%
awswrangler/catalog/_create.py | 198 | 10 | 0 | 95%
awswrangler/catalog/_definitions.py | 50 | 1 | 0 | 98%
awswrangler/catalog/_delete.py | 48 | 4 | 0 | 92%
awswrangler/catalog/_get.py | 228 | 21 | 0 | 91%
awswrangler/catalog/_utils.py | 83 | 3 | 0 | 96%
awswrangler/chime.py | 18 | 8 | 0 | 56%
awswrangler/cloudwatch.py | 62 | 4 | 0 | 94%
awswrangler/data_api/__init__.py | 2 | 0 | 0 | 100%
awswrangler/data_api/connector.py | 29 | 4 | 0 | 86%
awswrangler/data_api/rds.py | 63 | 2 | 0 | 97%
awswrangler/data_api/redshift.py | 75 | 4 | 0 | 95%
awswrangler/dynamodb/__init__.py | 5 | 0 | 0 | 100%
awswrangler/dynamodb/_delete.py | 15 | 0 | 0 | 100%
awswrangler/dynamodb/_read.py | 75 | 11 | 0 | 85%
awswrangler/dynamodb/_utils.py | 13 | 0 | 0 | 100%
awswrangler/dynamodb/_write.py | 32 | 9 | 0 | 72%
awswrangler/emr.py | 189 | 13 | 0 | 93%
awswrangler/exceptions.py | 29 | 0 | 0 | 100%
awswrangler/lakeformation/__init__.py | 3 | 0 | 0 | 100%
awswrangler/lakeformation/_read.py | 59 | 0 | 0 | 100%
awswrangler/lakeformation/_utils.py | 125 | 10 | 0 | 92%
awswrangler/mysql.py | 88 | 3 | 0 | 97%
awswrangler/neptune/__init__.py | 3 | 0 | 0 | 100%
awswrangler/neptune/_utils.py | 58 | 58 | 0 | 0%
awswrangler/neptune/client.py | 134 | 9 | 0 | 93%
awswrangler/neptune/gremlin_parser.py | 34 | 5 | 0 | 85%
awswrangler/neptune/neptune.py | 154 | 10 | 0 | 94%
awswrangler/opensearch/__init__.py | 4 | 0 | 0 | 100%
awswrangler/opensearch/_read.py | 55 | 4 | 0 | 93%
awswrangler/opensearch/_utils.py | 40 | 6 | 0 | 85%
awswrangler/opensearch/_write.py | 172 | 48 | 0 | 72%
awswrangler/oracle.py | 117 | 4 | 0 | 97%
awswrangler/postgresql.py | 83 | 3 | 0 | 96%
awswrangler/quicksight/__init__.py | 6 | 0 | 0 | 100%
awswrangler/quicksight/_cancel.py | 16 | 9 | 0 | 44%
awswrangler/quicksight/_create.py | 93 | 78 | 0 | 16%
awswrangler/quicksight/_delete.py | 73 | 35 | 0 | 52%
awswrangler/quicksight/_describe.py | 56 | 45 | 0 | 20%
awswrangler/quicksight/_get_list.py | 93 | 52 | 0 | 44%
awswrangler/quicksight/_utils.py | 20 | 12 | 0 | 40%
awswrangler/redshift.py | 308 | 18 | 0 | 94%
awswrangler/s3/__init__.py | 16 | 0 | 0 | 100%
awswrangler/s3/_copy.py | 71 | 0 | 0 | 100%
awswrangler/s3/_delete.py | 61 | 8 | 0 | 87%
awswrangler/s3/_describe.py | 48 | 0 | 0 | 100%
awswrangler/s3/_download.py | 16 | 0 | 0 | 100%
awswrangler/s3/_fs.py | 315 | 22 | 0 | 93%
awswrangler/s3/_list.py | 117 | 10 | 0 | 91%
awswrangler/s3/_merge_upsert_table.py | 45 | 0 | 0 | 100%
awswrangler/s3/_read.py | 105 | 5 | 0 | 95%
awswrangler/s3/_read_excel.py | 14 | 1 | 0 | 93%
awswrangler/s3/_read_parquet.py | 285 | 38 | 0 | 87%
awswrangler/s3/_read_text.py | 76 | 6 | 0 | 92%
awswrangler/s3/_select.py | 58 | 6 | 0 | 90%
awswrangler/s3/_upload.py | 16 | 0 | 0 | 100%
awswrangler/s3/_wait.py | 35 | 23 | 0 | 34%
awswrangler/s3/_write.py | 51 | 4 | 0 | 92%
awswrangler/s3/_write_concurrent.py | 35 | 0 | 0 | 100%
awswrangler/s3/_write_dataset.py | 97 | 9 | 0 | 91%
awswrangler/s3/_write_excel.py | 15 | 1 | 0 | 93%
awswrangler/s3/_write_parquet.py | 151 | 2 | 0 | 99%
awswrangler/s3/_write_text.py | 200 | 31 | 0 | 84%
awswrangler/secretsmanager.py | 17 | 1 | 0 | 94%
awswrangler/sqlserver.py | 98 | 4 | 0 | 96%
awswrangler/sts.py | 15 | 5 | 0 | 67%
awswrangler/timestream.py | 149 | 14 | 0 | 91%
Total | 7051 | 916 | 0 | 87%
```
We would need to understand why there is this difference with this workflow before merging this

**Pull request closed without merging**
