### PR TITLE
Remove `awswrangler.distributed` from coverage report

### PR DESCRIPTION
**Pull request by LeonLuttenberger**
### Feature or Bugfix
- Feature

### Detail
- Remove `awswrangler.distributed` from coverage report

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by malachi-constant** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: GitHubDistributedCodeBuild6-jWcl5DLmvupS
* Commit ID: 59bbf78bf5d5bf4d7a544de369be40332eef5686
* Result: SUCCEEDED
* [Build Logs](https://p0rshq9q5i.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=1b62d528-9ae2-43a8-a2d9-0bad54ec5937%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by malachi-constant** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: GitHubStandardCodeBuild8C06-llutOAimTATs
* Commit ID: 59bbf78bf5d5bf4d7a544de369be40332eef5686
* Result: SUCCEEDED
* [Build Logs](https://jsv9u8gote.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=270976bd-3255-4e6e-adee-e9a07ec6f4ca%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by malachi-constant** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: GitHubLoadTests5656BB24-ATYtnXPE7MOa
* Commit ID: 59bbf78bf5d5bf4d7a544de369be40332eef5686
* Result: SUCCEEDED
* [Build Logs](https://i1emq028pj.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=5cc9602c-f787-4663-9029-6ff5a9e92363%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Review by jaidisido — COMMENTED** [review]
I was thinking of something a bit more dynamic perhaps? If the CB is distributed then perhaps we should include this directory. The difficulty then is excluding all the non-distributed methods when running the distributed CB...

**Comment by LeonLuttenberger** [comment]
> I was thinking of something a bit more dynamic perhaps? If the CB is distributed then perhaps we should include this directory. The difficulty then is excluding all the non-distributed methods when running the distributed CB...

I agree this would be ideal. The problem is that this directory exclusion can only be defined in a config file, and can't be a CLI parameter. So we would need to either have two configuration files, or using `sed` to edit the configuration file from the tox script somehow.

Another huge issue is that coverage is kind of useless when we use Ray. Pytest tracks coverage by following the main process' execution. When we distributed with Ray, we create a local Ray cluster, so the main process never actually executes the distributed code. This makes it essentially invisible to the coverage report. I think there might be a way to fix it by [specifying local_mode](https://github.com/ray-project/ray/issues/9059#issuecomment-651572309), but I need to investigate this more.

**Review by jaidisido — APPROVED** [review]

**Review by malachi-constant — APPROVED** [review]

**Pull request merged**
