### PR TITLE
Dependency: Pandas Version

### PR DESCRIPTION
**Pull request by malachi-constant**
### Dependency Update
- Pandas version `>= 1.5.0` causing memory leak issues in some of our methods.

### Detail
- Locking version to `<= 1.4.4` until resolved on the pandas side.

### Relates
- #1678 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by malachi-constant** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: GitHubCodeBuild8756EF16-4rfo0GHQ0u9a
* Commit ID: 0efd739b42aa150d382a61dd43910984a64243a7
* Result: SUCCEEDED
* [Build Logs](https://gqgcj9s2gc.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=6f2c387e-c0e6-4b4a-95a6-cfde6feeee62%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by jaidisido** [comment]
Could we find or raise the actual issue causing this with pandas? I would want to avoid pinning the library until we understand why at least, specially that we need pandas 1.5.0+ for our 3.0.0 release

**Comment by malachi-constant** [comment]
> Could we find or raise the actual issue causing this with pandas? I would want to avoid pinning the library until we understand why at least, specially that we need pandas 1.5.0+ for our 3.0.0 release

Yep, I'm working on finding where memory leak happens using `memory_profiler` hopefully I'll know more after today.

**Comment by malachi-constant** [comment]
> Could we find or raise the actual issue causing this with pandas? I would want to avoid pinning the library until we understand why at least, specially that we need pandas 1.5.0+ for our 3.0.0 release

@jaidisido [Confirmed](https://github.com/aws/aws-sdk-pandas/issues/1678#issuecomment-1286292514) this is no longer an issue with 1.5.1 users will need to be on python3.8 or newer.

**Comment by malachi-constant** [comment]
I'm not sure if this is the convention to exempt a dep version for the library, let me know.

**Comment by malachi-constant** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: GitHubCodeBuild8756EF16-4rfo0GHQ0u9a
* Commit ID: 9f7681067e2939f9bb46107b0e67b07353c3813e
* Result: FAILED
* [Build Logs](https://gqgcj9s2gc.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=106a5003-aa0a-42bf-b288-52b1b07cd42b%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by malachi-constant** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: GitHubCodeBuild8756EF16-4rfo0GHQ0u9a
* Commit ID: 274ed6a8aab7fefa57e6f4ed9c09b00efb46b64a
* Result: FAILED
* [Build Logs](https://gqgcj9s2gc.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=19de8346-637e-4811-8f66-fec8463af386%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Review by jaidisido — APPROVED** [review]

**Comment by jaidisido** [comment]
Great deep dive on this one @malachi-constant , thanks!

**Review by LeonLuttenberger — APPROVED** [review]

**Comment by malachi-constant** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: GitHubCodeBuild8756EF16-4rfo0GHQ0u9a
* Commit ID: fb962444650e217ef3c7e233c0768afe35c106d0
* Result: FAILED
* [Build Logs](https://gqgcj9s2gc.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=47e66ef9-ba45-4f92-aab3-3ce7c813e755%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Pull request merged**
