### PR TITLE
enhancement: Add timestream common attributes

### LINKED ISSUE #2082: Add Common Attributes to Timestream write
Writing to Timestream with common attributes like dimensions can make a massive cost difference (size of the attributes * number of rows). Right now, you can supply dimension columns, but that requires two things that are inefficient. 

1) adding a repetitive column to a potentially massive dataframe if it does not already exist 
2) writing these repetitive values to each record rather than once per 100-record batch

**Describe the solution you'd like**
One thing that would be great would be to specify, at the dataframe level, a dictionary of common attributes to be passed with all record batches in the frame, assuming they are all consistent.

e.g., if I have a CSV I am reading from that will all be from the same IOT device, I should be able to specify comething like
```
common_attributes = {
            'Dimensions': {‘Name’: ‘device_id’, ‘Value’: ‘12345’},
            'MeasureValueType': 'DOUBLE',
            'MeasureName': measure_name,
        }
````

The most flexible solution would be for a user to supply common_attribute columns when calling `wr.timestream.write`. When processing the dataframe, the library should groupby the specified columns and then send the batches from subgroups with the specified common attributes.
 
**Describe alternatives you've considered**
The solution I’m using on my end right now involves specifying a group id column to the dataframe and looping through using a dictionary specifying the common attributes for that group.

### PR DESCRIPTION
**Pull request by jaidisido**
### Feature or Bugfix

- Enhancement

### Detail
- Add timestream common attributes

TimestreamWrite exposes a [CommonAttributes](https://docs.aws.amazon.com/timestream/latest/developerguide/API_WriteRecords.html#timestream-WriteRecords-request-CommonAttributes) argument which enables the user to supply attributes that are applied to all write operations. For instance common dimensions or measure names.

This has two benefits:
1. It reduces the size of the input data frame
2. It reduces the size of the payload for each write call and thus reduces the cost

Introducing this argument means that other arguments must become optional (`time_col`, `measure_col`, `dimension_cols`...) because they can be supplied via the common_attributes instead

### Relates
- closes #2082

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by malachi-constant** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: GitHubCodeBuild8756EF16-4rfo0GHQ0u9a
* Commit ID: fc47098aac45eee7894484a68db8f8e652f6a383
* Result: FAILED
* [Build Logs](https://gqgcj9s2gc.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=9b228728-ce81-4c08-aaa5-81fc8992dc79%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by malachi-constant** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: GitHubCodeBuild8756EF16-4rfo0GHQ0u9a
* Commit ID: 801177ecfbc7e1f5fe9bb14f1b19dfd3510dd8a2
* Result: FAILED
* [Build Logs](https://gqgcj9s2gc.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=af541571-19ec-4701-ae36-910b13c35dbc%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Review by malachi-constant — APPROVED** [review]
LGTM

**Review by kukushking — APPROVED** [review]
Looks good!

**Pull request merged**
