### PR TITLE
(feat) Add distributed wr.redshift.read_sql_* && to_sql

### PR DESCRIPTION
**Pull request by kukushking**
### Feature or Bugfix
- Feature

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by malachi-constant** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: GitHubDistributedCodeBuild6-jWcl5DLmvupS
* Commit ID: f61b4692da51a452dba76f8063d9a7f873a31e64
* Result: FAILED
* [Build Logs](https://p0rshq9q5i.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=20df80ef-0311-41c8-bc70-a54884ee7808%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by malachi-constant** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: GitHubStandardCodeBuild8C06-llutOAimTATs
* Commit ID: f61b4692da51a452dba76f8063d9a7f873a31e64
* Result: SUCCEEDED
* [Build Logs](https://jsv9u8gote.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=a7a98d47-97aa-4c25-82eb-cf76857b9b8c%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by malachi-constant** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: GitHubLoadTests5656BB24-ATYtnXPE7MOa
* Commit ID: f61b4692da51a452dba76f8063d9a7f873a31e64
* Result: FAILED
* [Build Logs](https://i1emq028pj.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=45da3028-1609-40d6-9322-2ec581c07852%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Review by jaidisido — COMMENTED** [review]
How is this different from using `unload`?

If there is no difference, then I am not sure I am in favour of mixing both. `read_sql_query` has been designed for small loads, it's even mentioned in the notes:
```
For large extractions (1K+ rows) consider the function **wr.redshift.unload()**.
```
so I am not sure why we would want to allow unload here for the special distributed case when the user can simply use an existing method for that. Seems like tech debt for no benefit

**Comment by kukushking** [comment]
@jaidisido It is indeed using `unload_to_files` + `read_parquet` behind the scenes. Do we still want to stick to the idea of being able to scale without having to change the code simply by moving to a Ray cluster? It would be nice from user perspective to keep the same experience for `read_sql_query`.

Actually now that you mentioned it, it looks like there are a lot of similarities between `read_sql_query / unload` (and `to_sql / copy` for that matter), as they're designed to do the same thing in different ways and for different data sizes, to the point where it seems it might make sense to make them "modes" of the same API. Kind of similar to what we did with CTAS/UNLOAD in Athena module. Could be a potential refactoring for 3.0, what do you think?

**Comment by kukushking** [comment]
Converting PR to draft until the convo around API coverage and refactoring is agreed on

**Pull request closed without merging**
