### PR TITLE
feat: manage `NULL` values in `athena.to_iceberg` merge statement

### PR DESCRIPTION
**Pull request by aldder**
### Feature or Bugfix
- Feature

### Detail

When performing a merge operation between two Iceberg tables on Athena, join fields that contain NULL values do not 
match with corresponding NULL values in the other table. This issue is due to the generic behavior in SQL where NULL != NULL. As a result, rows with NULL values in the join columns fail to find matches, causing incomplete merges and data inconsistencies.

This pull request implement this feature by extending the join condition to account for NULL values. The enhanced join condition ensures that rows with NULL values in the join columns are correctly matched with corresponding rows in the other table that also have NULL values. 

The following example illustrates the differences between join condition:
- join condition that doesn't handle null values
```
MERGE INTO table1 target
USING table2 source
ON 
    target.field1 = source.field1 AND target.field2=source AND ...
WHEN MATCHED THEN ...
WHEN NOT MATCHED THEN ...
```

- join condition that does handle null values
```
MERGE INTO table1 target
USING table2 source
ON
    (target.field1 = source.field1 OR (target.field1 IS NULL AND source.field1 IS NULL)) AND
    (target.field2 = source.field2 OR (target.field2 IS NULL AND source.field2 IS NULL)) AND
    ...
WHEN MATCHED THEN ...
WHEN NOT MATCHED THEN ...
```

Example use-case:

df1:
```
| field1   |   field2 | action   |
|:---------|---------:|:---------|
| a        |      0.0 | insert   |
| a        |      1.1 | insert   |
| a        |    nan   | insert   |
| nan      |      2.2 | insert   |

wr.athena.to_iceberg(df1, ...)
```

df2:
```
| field1   |   field2 | action   |
|:---------|---------:|:---------|
| a        |      1.1 | update   |
| a        |    nan   | update   |
| nan      |      2.2 | update   |
| b        |      3.3 | insert   |

wr.athena.to_iceberg(df2, merge_cols=['field1','field2'], ...)
```
:x: current output:
```
| field1   |   field2 | action   |
|:---------|---------:|:---------|
| a        |      0.0 | insert   | [OK] old field untouched as no match found
| a        |      1.1 | update   | [OK] old field updated as a match has been found
| a        |    nan   | insert   | [KO] old pair (a, nan) should've been updated
| a        |    nan   | update   | [KO] new pair (a, nan) has been inserted without matching with previous one
| nan      |      2.2 | insert   | [KO] old pair (nan, 2.2) should've been updated
| nan      |      2.2 | update   | [KO] new pair (nan, 2.2) has been inserted without matching with previous one
| b        |      3.3 | insert   | [OK] new field inserted as didn't find a match
```
:white_check_mark: expected output:
```
| field1   |   field2 | action   |
|:---------|---------:|:---------|
| a        |      0.0 | insert   |
| a        |      1.1 | update   |
| a        |    nan   | update   |
| nan      |      2.2 | update   |
| b        |      3.3 | insert   |
```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by malachi-constant** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: GitHubCodeBuild8756EF16-4rfo0GHQ0u9a
* Commit ID: c08e5dbc44096bdfa4c60cce76439e65d30a238c
* Result: FAILED
* [Build Logs](https://gqgcj9s2gc.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=68e826a1-5da6-498b-879a-b9131dc8f43c%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by malachi-constant** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: GitHubCodeBuild8756EF16-4rfo0GHQ0u9a
* Commit ID: 6f8da20d58e97debb621985b49d0de684191bfb2
* Result: FAILED
* [Build Logs](https://gqgcj9s2gc.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=fa19ae4b-cc78-4588-a820-a10bf7500beb%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by malachi-constant** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: GitHubDistributedCodeBuild6-jWcl5DLmvupS
* Commit ID: c08e5dbc44096bdfa4c60cce76439e65d30a238c
* Result: FAILED
* [Build Logs](https://p0rshq9q5i.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=5e17025f-fc3c-448c-b5ac-eb6149fb9bf3%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by malachi-constant** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: GitHubDistributedCodeBuild6-jWcl5DLmvupS
* Commit ID: 6f8da20d58e97debb621985b49d0de684191bfb2
* Result: FAILED
* [Build Logs](https://p0rshq9q5i.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=c5b8ea1b-8d0c-49c9-a05c-e50730fb6129%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by malachi-constant** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: GitHubCodeBuild8756EF16-4rfo0GHQ0u9a
* Commit ID: dd2facf1d08c5d9496ae404a49d3838c0f2a5691
* Result: SUCCEEDED
* [Build Logs](https://gqgcj9s2gc.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=6adc7192-f696-4ad2-89bd-ad3372981b9e%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by malachi-constant** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: GitHubDistributedCodeBuild6-jWcl5DLmvupS
* Commit ID: dd2facf1d08c5d9496ae404a49d3838c0f2a5691
* Result: SUCCEEDED
* [Build Logs](https://p0rshq9q5i.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=00e0ea64-01b2-4113-8989-5f3ced3a05b1%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Review by jaidisido — APPROVED** [review]

**Review by kukushking — APPROVED** [review]
Thank you!

**Comment by malachi-constant** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: GitHubCodeBuild8756EF16-4rfo0GHQ0u9a
* Commit ID: 1c287a6a89b8a081cfc7863c36292245596b94a6
* Result: SUCCEEDED
* [Build Logs](https://gqgcj9s2gc.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=1f61554c-fdb4-4f70-a2b6-cf26138ca653%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by malachi-constant** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: GitHubDistributedCodeBuild6-jWcl5DLmvupS
* Commit ID: 1c287a6a89b8a081cfc7863c36292245596b94a6
* Result: SUCCEEDED
* [Build Logs](https://p0rshq9q5i.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=bf58e8ea-3557-456e-a3d2-e858446fe1a9%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by brendan-cook-87** [comment]
hmm... this particular change seems to be causing some pretty bad performance issues with some of my production tables where there are guaranteed no nulls in my ids that I am trying to merge on...

I'm talking a 5s merge operation taking 18 minutes. and then taking 5s again when I delete the (target.field1 IS NULL AND source.field1 IS NULL) clause.

Would you accept a patch to add a flag to toggle this handle_nulls behaviour in the join operation?

**Pull request merged**
